Tell where to get vars if required.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -465,7 +465,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar build build_cpu build_vendor build_os host host_cpu host_vendor host_os CYGWIN_TRUE CYGWIN_FALSE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE YACC LEX LEXLIB LEX_OUTPUT_ROOT EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL VARS_CONFIG VARS_CFLAGS VARS_LIBS WISH tkifm PERL ifm2dev ifm2tex scr2ifm LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar VARS_CONFIG VARS_CFLAGS VARS_LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CYGWIN_TRUE CYGWIN_FALSE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE YACC LEX LEXLIB LEX_OUTPUT_ROOT EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL WISH tkifm PERL ifm2dev ifm2tex scr2ifm LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1949,6 +1949,121 @@ am__tar='${AMTAR} chof - "$$tardir"'; am__untar='${AMTAR} xf -'
 
 
           ac_config_headers="$ac_config_headers etc/config.h"
+
+
+
+if test `perl -e '
+sub canonical {
+    $str = shift;
+    $str =~ s/\D+/./g;
+    join("", map {sprintf("%06s", $_)} split(/\./i, $str));
+}
+
+$actual = canonical(shift);
+$required = canonical(shift);
+
+print $required <= $actual ? "yes" : "no";'  ` = no; then
+   { { echo "$as_me:$LINENO: error: version  or greater is required" >&5
+echo "$as_me: error: version  or greater is required" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+# Extract the first word of "vars-config", so it can be a program name with args.
+set dummy vars-config; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_VARS_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $VARS_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_VARS_CONFIG="$VARS_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_VARS_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_VARS_CONFIG" && ac_cv_path_VARS_CONFIG="no"
+  ;;
+esac
+fi
+VARS_CONFIG=$ac_cv_path_VARS_CONFIG
+
+if test -n "$VARS_CONFIG"; then
+  echo "$as_me:$LINENO: result: $VARS_CONFIG" >&5
+echo "${ECHO_T}$VARS_CONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+HAVE_VARS=
+if test $VARS_CONFIG != no; then
+   # Check version if required.
+   if test -n "2.6" && test 2.6 != yes; then
+      echo "$as_me:$LINENO: checking for Vars - version >= 2.6" >&5
+echo $ECHO_N "checking for Vars - version >= 2.6... $ECHO_C" >&6
+      VARS_VERSION=`$VARS_CONFIG --version`
+      echo "$as_me:$LINENO: result: $VARS_VERSION" >&5
+echo "${ECHO_T}$VARS_VERSION" >&6
+
+if test `perl -e '
+sub canonical {
+    $str = shift;
+    $str =~ s/\D+/./g;
+    join("", map {sprintf("%06s", $_)} split(/\./i, $str));
+}
+
+$actual = canonical(shift);
+$required = canonical(shift);
+
+print $required <= $actual ? "yes" : "no";' $VARS_VERSION 2.6` = no; then
+   { { echo "$as_me:$LINENO: error: Vars library version 2.6 or greater is required" >&5
+echo "$as_me: error: Vars library version 2.6 or greater is required" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+   fi
+
+   # Define HAVE_PREFIX.
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_VARS 1
+_ACEOF
+
+   HAVE_VARS=yes
+
+   # Set CFLAGS.
+   VARS_CFLAGS="`$VARS_CONFIG --cflags`"
+
+
+   # Set LIBS.
+   VARS_LIBS="`$VARS_CONFIG --libs`"
+
+elif test -n "2.6"; then
+   if test -z "the Vars library is required -- get it from www.freewebtown.com/zondo/programs"; then
+      { { echo "$as_me:$LINENO: error: can't find Vars library" >&5
+echo "$as_me: error: can't find Vars library" >&2;}
+   { (exit 1); exit 1; }; }
+   else
+      { { echo "$as_me:$LINENO: error: the Vars library is required -- get it from www.freewebtown.com/zondo/programs" >&5
+echo "$as_me: error: the Vars library is required -- get it from www.freewebtown.com/zondo/programs" >&2;}
+   { (exit 1); exit 1; }; }
+   fi
+fi
 
 
 # Make sure we can run config.sub.
@@ -4127,7 +4242,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4130 "configure"' > conftest.$ac_ext
+  echo '#line 4245 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5699,7 +5814,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5702:" \
+echo "$as_me:5817:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6749,11 +6864,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6752: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6867: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6756: \$? = $ac_status" >&5
+   echo "$as_me:6871: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6992,11 +7107,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6995: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7110: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6999: \$? = $ac_status" >&5
+   echo "$as_me:7114: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -7052,11 +7167,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7055: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7170: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7059: \$? = $ac_status" >&5
+   echo "$as_me:7174: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9237,7 +9352,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9240 "configure"
+#line 9355 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9335,7 +9450,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9338 "configure"
+#line 9453 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11524,11 +11639,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11527: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11642: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11531: \$? = $ac_status" >&5
+   echo "$as_me:11646: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11584,11 +11699,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11587: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11702: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11591: \$? = $ac_status" >&5
+   echo "$as_me:11706: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12945,7 +13060,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12948 "configure"
+#line 13063 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13043,7 +13158,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13046 "configure"
+#line 13161 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13880,11 +13995,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13883: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13998: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13887: \$? = $ac_status" >&5
+   echo "$as_me:14002: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13940,11 +14055,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13943: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14058: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13947: \$? = $ac_status" >&5
+   echo "$as_me:14062: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15975,11 +16090,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15978: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16093: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15982: \$? = $ac_status" >&5
+   echo "$as_me:16097: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -16218,11 +16333,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16221: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16336: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16225: \$? = $ac_status" >&5
+   echo "$as_me:16340: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -16278,11 +16393,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16281: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16396: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16285: \$? = $ac_status" >&5
+   echo "$as_me:16400: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18463,7 +18578,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18466 "configure"
+#line 18581 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18561,7 +18676,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18564 "configure"
+#line 18679 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19743,115 +19858,6 @@ _ACEOF
 fi
 
 
-
-if test `perl -e '
-sub canonical {
-    $str = shift;
-    $str =~ s/\D+/./g;
-    join("", map {sprintf("%06s", $_)} split(/\./i, $str));
-}
-
-$actual = canonical(shift);
-$required = canonical(shift);
-
-print $required <= $actual ? "yes" : "no";'  ` = no; then
-   { { echo "$as_me:$LINENO: error: version  or greater is required" >&5
-echo "$as_me: error: version  or greater is required" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-
-# Extract the first word of "vars-config", so it can be a program name with args.
-set dummy vars-config; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_path_VARS_CONFIG+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $VARS_CONFIG in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_VARS_CONFIG="$VARS_CONFIG" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_path_VARS_CONFIG="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-  test -z "$ac_cv_path_VARS_CONFIG" && ac_cv_path_VARS_CONFIG="no"
-  ;;
-esac
-fi
-VARS_CONFIG=$ac_cv_path_VARS_CONFIG
-
-if test -n "$VARS_CONFIG"; then
-  echo "$as_me:$LINENO: result: $VARS_CONFIG" >&5
-echo "${ECHO_T}$VARS_CONFIG" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-
-HAVE_VARS=
-if test $VARS_CONFIG != no; then
-   # Check version if required.
-   if test -n "2.6" && test 2.6 != yes; then
-      echo "$as_me:$LINENO: checking for Vars - version >= 2.6" >&5
-echo $ECHO_N "checking for Vars - version >= 2.6... $ECHO_C" >&6
-      VARS_VERSION=`$VARS_CONFIG --version`
-      echo "$as_me:$LINENO: result: $VARS_VERSION" >&5
-echo "${ECHO_T}$VARS_VERSION" >&6
-
-if test `perl -e '
-sub canonical {
-    $str = shift;
-    $str =~ s/\D+/./g;
-    join("", map {sprintf("%06s", $_)} split(/\./i, $str));
-}
-
-$actual = canonical(shift);
-$required = canonical(shift);
-
-print $required <= $actual ? "yes" : "no";' $VARS_VERSION 2.6` = no; then
-   { { echo "$as_me:$LINENO: error: Vars library version 2.6 or greater is required" >&5
-echo "$as_me: error: Vars library version 2.6 or greater is required" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-   fi
-
-   # Define HAVE_PREFIX.
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_VARS 1
-_ACEOF
-
-   HAVE_VARS=yes
-
-   # Set CFLAGS.
-   VARS_CFLAGS="`$VARS_CONFIG --cflags`"
-
-
-   # Set LIBS.
-   VARS_LIBS="`$VARS_CONFIG --libs`"
-
-elif test -n "2.6"; then
-   { { echo "$as_me:$LINENO: error: can't find Vars library" >&5
-echo "$as_me: error: can't find Vars library" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-
 for ac_prog in wish8.0 wish80 wish
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
@@ -20652,6 +20658,9 @@ s,@am__leading_dot@,$am__leading_dot,;t t
 s,@AMTAR@,$AMTAR,;t t
 s,@am__tar@,$am__tar,;t t
 s,@am__untar@,$am__untar,;t t
+s,@VARS_CONFIG@,$VARS_CONFIG,;t t
+s,@VARS_CFLAGS@,$VARS_CFLAGS,;t t
+s,@VARS_LIBS@,$VARS_LIBS,;t t
 s,@build@,$build,;t t
 s,@build_cpu@,$build_cpu,;t t
 s,@build_vendor@,$build_vendor,;t t
@@ -20701,9 +20710,6 @@ s,@F77@,$F77,;t t
 s,@FFLAGS@,$FFLAGS,;t t
 s,@ac_ct_F77@,$ac_ct_F77,;t t
 s,@LIBTOOL@,$LIBTOOL,;t t
-s,@VARS_CONFIG@,$VARS_CONFIG,;t t
-s,@VARS_CFLAGS@,$VARS_CFLAGS,;t t
-s,@VARS_LIBS@,$VARS_LIBS,;t t
 s,@WISH@,$WISH,;t t
 s,@tkifm@,$tkifm,;t t
 s,@PERL@,$PERL,;t t
